package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme
val PrimaryLight = Color(0xFF006C51)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF8CF4D0)
val OnPrimaryContainerLight = Color(0xFF002117)
val SecondaryLight = Color(0xFF4C6358)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE9DA)
val OnSecondaryContainerLight = Color(0xFF082017)
val TertiaryLight = Color(0xFF3F6374)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC3E8FD)
val OnTertiaryContainerLight = Color(0xFF001F2A)
val BackgroundLight = Color(0xFFFBFDFA)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF191C1B)
val SurfaceVariantLight = Color(0xFFDBE5DE)
val OnSurfaceVariantLight = Color(0xFF404944)
val OutlineLight = Color(0xFF707974)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)

// Dark Scheme
val PrimaryDark = Color(0xFF6FD7B5)
val OnPrimaryDark = Color(0xFF003829)
val PrimaryContainerDark = Color(0xFF00513C)
val OnPrimaryContainerDark = Color(0xFF8CF4D0)
val SecondaryDark = Color(0xFFB3CCBF)
val OnSecondaryDark = Color(0xFF1E352C)
val SecondaryContainerDark = Color(0xFF354B42)
val OnSecondaryContainerDark = Color(0xFFCEE9DA)
val TertiaryDark = Color(0xFFA7CCE0)
val OnTertiaryDark = Color(0xFF0A3444)
val TertiaryContainerDark = Color(0xFF264B5C)
val OnTertiaryContainerDark = Color(0xFFC3E8FD)
val BackgroundDark = Color(0xFF111413)
val OnBackgroundDark = Color(0xFFE1E3DF)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE1E3DF)
val SurfaceVariantDark = Color(0xFF404944)
val OnSurfaceVariantDark = Color(0xFFBFC9C3)
val OutlineDark = Color(0xFF89938D)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

// Financial semantic colors
val IncomeGreenLight = Color(0xFF15803D)
val IncomeGreenDark = Color(0xFF4ADE80)
val ExpenseRedLight = Color(0xFFB91C1C)
val ExpenseRedDark = Color(0xFFF87171)
val WarningAmberLight = Color(0xFFB45309)
val WarningAmberDark = Color(0xFFFBBF24)
